export const ADD_PRODUCTS = 'ADD_PRODUCTS'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const TOGGLE_PRODUCT = 'TOGGLE_PRODUCT'
export const FILL_FIELDS = 'FILL_FIELDS'

export const ADD_CLIENTS = 'ADD_CLIENTS'
export const ADD_CLIENT = 'ADD_CLIENT'
