export const GET_PRODUTO_PAGINACAO = 'produtos/get_produtos_paginacao.php'
export const GET_PRODUTO_POR_NOME = 'produtos/get_produto_por_nome.php'
export const GET_PRODUTO_POR_ID = 'produtos/get_produto_por_id.php'
export const PUT_PRODUTO = 'produtos/put_produto.php'
export const EDIT_PRODUTO = 'produtos/edit_produto.php'
export const DELETE_PRODUTO = 'produtos/delete_produto.php'